from reportlab.platypus import SimpleDocTemplate, Paragraph, PageBreak
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.lib.styles import getSampleStyleSheet
import time

pdf = SimpleDocTemplate(filename="table_of_contents2.pdf")


# def begin(self, name='', typ=''):
stylesheet = getSampleStyleSheet()
code = stylesheet['Code']
bt = stylesheet['BodyText']
story = []

# Cover page
t = time.gmtime(time.time())
timestring = time.strftime("%d-%m-%Y %H:%M", t)
story.append(Paragraph('<font size=18>Documentation for</font>', bt))
story.append(Paragraph('<font size=18>Generated by: graphdocpy.py version %s</font>' % '__version__', bt))
story.append(Paragraph('<font size=18>Date generated: %s</font>' % timestring, bt))
story.append(Paragraph('<font size=18>Format: PDF</font>', bt))
story.append(PageBreak())

# Table of contents
toc = TableOfContents()
story.append(toc)
story.append(PageBreak())

pdf.build(flowables=story)
