# Generated by Django 3.2.4 on 2021-07-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='age',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
